apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mailu-admin-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/permanent-redirect: "https://mail.kliu.io/admin/ui/"
    nginx.ingress.kubernetes.io/follow-redirects: "true"
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  tls:
  - hosts: {{ toYaml .Values.mailu.hosts | nindent 4 }}
    secretName: mailu-tls # If unsure how to generate these, check out https://github.com/ployst/docker-letsencrypt
  rules:
  {{- range .Values.mailu.hosts }}
  - host: "{{ . }}"
    http:
      paths:
      - path: "/admin"
        backend:
          serviceName: admin
          servicePort: 80
  {{- end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mailu-admin-ui-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: "/ui/$2"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /admin;
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  tls:
  - hosts: {{ toYaml .Values.mailu.hosts | nindent 4 }}
    secretName: mailu-tls # If unsure how to generate these, check out https://github.com/ployst/docker-letsencrypt
  rules:
  {{- range .Values.mailu.hosts }}
  - host: "{{ . }}"
    http:
      paths:
      - path: "/admin/ui(/|$)(.*)"
        backend:
          serviceName: admin
          servicePort: 80
  {{- end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mailu-admin-static-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: "/static/$2"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /admin;
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  tls:
  - hosts: {{ toYaml .Values.mailu.hosts | nindent 4 }}
    secretName: mailu-tls # If unsure how to generate these, check out https://github.com/ployst/docker-letsencrypt
  rules:
  {{- range .Values.mailu.hosts }}
  - host: "{{ . }}"
    http:
      paths:
      - path: "/admin/static(/|$)(.*)"
        backend:
          serviceName: admin
          servicePort: 80
  {{- end }}