apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: mailu-front
  namespace: default
  labels:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
spec:
  selector:
    matchLabels:
      k8s-app: mail-loadbalancer
      component: ingress-controller
      type: nginx
  template:
    metadata:
      labels:
        k8s-app: mail-loadbalancer
        component: ingress-controller
        type: nginx
    spec:
      # hostNetwork: true
      # nodeSelector:
      #   kubernetes.io/hostname: rem
      # dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: front
        image: mailu/nginx:1.7
        envFrom:
          - configMapRef:
              name: mailu-config
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: nginx-config
            mountPath: /conf/tls.conf
            subPath: tls.conf
        ports:
          - name: pop3
            containerPort: 110
            protocol: TCP
          - name: pop3s
            containerPort: 995
            protocol: TCP
          - name: imap
            containerPort: 143
            protocol: TCP
          - name: imaps
            containerPort: 993
            protocol: TCP
          - name: smtp
            containerPort: 25
            protocol: TCP
          - name: smtp-auth
            containerPort: 10025
            protocol: TCP
          - name: imap-auth
            containerPort: 10143
            protocol: TCP
          - name: smtps
            containerPort: 465
            protocol: TCP
          - name: smtpd
            containerPort: 587
            protocol: TCP
          - name: auth
            containerPort: 8000
            protocol: TCP
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
      volumes:
        - name: certs
          secret:
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
            secretName: mailu-tls
        - name: nginx-config
          configMap:
            name: mailu-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: default
  labels:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
spec:
  selector:
    k8s-app: mail-loadbalancer
    component: ingress-controller
    type: nginx
  ports:
  - name: pop3
    port: 110
    protocol: TCP
  - name: pop3s
    port: 995
    protocol: TCP
  - name: imap
    port: 143
    protocol: TCP
  - name: imaps
    port: 993
    protocol: TCP
  - name: smtp
    port: 25
    protocol: TCP
  - name: smtps
    port: 465
    protocol: TCP
  - name: smtpd
    port: 587
    protocol: TCP
  - name: smtp-auth
    port: 10025
    protocol: TCP
  - name: imap-auth
    port: 10143
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailu-nginx-config
data:
  tls.conf: |
    # Increase SSL protocol support for older mail clients
    # E.g. Synapse as of 2019-09-27
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    ssl_certificate {{ "{{" }} TLS[0] {{ "}}" }};
    ssl_certificate_key {{ "{{" }} TLS[1] {{ "}}" }};
    ssl_dhparam /conf/dhparam.pem;