apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mailu-antispam-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/auth-url: http://admin.default.svc.cluster.local/internal/auth/admin
    # Following snippet sets the password automatically because you're approved by the auth-url
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Password "mailu";
  labels:
    app: mailu
    role: mail
    tier: frontend
spec:
  tls:
  - hosts: {{ toYaml .Values.mailu.hosts | nindent 4 }}
    secretName: mailu-tls # If unsure how to generate these, check out https://github.com/ployst/docker-letsencrypt
  rules:
  {{- range .Values.mailu.hosts }}
  - host: "{{ . }}"
    http:
      paths:
      - path: "/admin/antispam(/|$)(.*)"
        backend:
          serviceName: antispam
          servicePort: 11334
  {{- end }}