apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mailu-webmail-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  tls:
  - hosts:
    - "mail.potatofrom.space"
    secretName: letsencrypt-webmail # If unsure how to generate these, check out https://github.com/ployst/docker-letsencrypt
  rules:
    - host: "mail.potatofrom.space"
      http:
        paths:
        - path: /webmail(/|$)(.*)
          backend:
            serviceName: webmail
            servicePort: 80