{{- $fullName := include "nextcloud.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullName }}-onlyoffice
  labels:
    app: {{ template "nextcloud.name" . }}
    chart: {{ template "nextcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "nextcloud.name" . }}-onlyoffice
    spec:
      containers:
      - image: onlyoffice/documentserver:latest
        name: onlyoffice
        # OnlyOffice requires STDIN and TTY attached—see
        # https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/63
        stdin: true
        tty: true
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 3
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-onlyoffice
  labels:
    app: {{ template "nextcloud.name" . }}
    chart: {{ template "nextcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: {{ template "nextcloud.name" . }}-onlyoffice