apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: blog
spec:
  tls:
    - secretName: blog-tls
      hosts:
        - kliu.io
        - www.kliu.io
  rules:
    - host: kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: blog
              servicePort: 80
    - host: www.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: blog
              servicePort: 80
