apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kevin@potatofrom.space
    privateKeySecretRef:
      name: letsencrypt-prod
  ## Configure the challenge solvers.
  solvers:
  # An empty selector will 'match' all Certificate resources that
  # reference this Issuer.
  - selector: {}
    http01:
      ingress:
        class: ""