minecraftServer:
  motd: "Vanilla / Kevloo Hosting"
  jvmOpts: -Xmx1G
  jvmXxOpts: "-XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:UseSSE=3"
  type: SPIGOT
  version: 1.14.2
  difficulty: normal
  levelSeed: "-1469446201797389856"
  port: 25566
  query:
    port: 25566
  ops:
    - nitroignika
securityContext:
  runAsUser: 1007
  fsGroup: 100
