minecraftServer:
  motd: "RLCraft - Potato Hosting"
  type: FORGE
  version: 1.12.2
  memory: 4G
  jvmXxOpts: "-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
  forgeVersion: 14.23.5.2838
  difficulty: hard
  port: 25569
  query:
    port: 25569
  ops: [Pneumaticat]
securityContext:
  runAsUser: 1000
  fsGroup: 100
