alertmanager:
  config:
    global:
      smtp_from: alert@kliu.io
      smtp_smarthost: kliu.io:587
      smtp_auth_username: alert@kliu.io
    route:
      receiver: email
      routes: []
    receivers:
    - name: email
      email_configs:
      - to: kevin@kliu.io
additionalPrometheusRulesMap:
  alert-rules:
    groups:
    - name: general.rules
      rules:
      - alert: LowDiskSpace
        annotations:
          summary: "Instance {{ $labels.instance }} is low on disk space"
          description: "Go fix."
        for: 10m
        expr: node_filesystem_avail_bytes{mountpoint="/"} < 20*1024*1024*1024
        labels:
          severity: warning
defaultRules:
  create: false
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'node'
      static_configs:
      - targets: [
          'karmaxer.i.kliu.io:9100',
          'rem.i.kliu.io:9100',
          '192.168.1.17:9100'
        ]
    # Required for additional scrape configs as said by
    # https://stackoverflow.com/questions/59201108/how-to-enable-additional-configs-for-prometheus-operator
    serviceMonitorSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              # Size below should match your existing PV's size
              storage: 10Gi
prometheusOperator:
  createCustomResource: false
grafana:
  enabled: true
  persistence:
    enabled: true
  admin:
    existingSecret: grafana-credentials
  ingress:
    enabled: true
    hosts: [grafana.kliu.io]
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.kliu.io
    annotations:
      kubernetes.io/tls-acme: "true"