apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        envFrom:
        - secretRef:
            name: gitlab
        volumeMounts:
        - name: gitlab-data
          mountPath: /etc/gitlab  
          subPath: config
        - name: gitlab-data
          mountPath: /var/opt/gitlab
          subPath: data
        - name: gitlab-data
          mountPath: /var/log/gitlab
          subPath: logs
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data