apiVersion: v1
kind: Secret
metadata:
  name: gitlab
type: Opaque
stringData:
  GITLAB_OMNIBUS_CONFIG: |
    external_url 'https://gitlab.kliu.io'
    unicorn['worker_processes'] = 2
    # Add any other gitlab.rb configuration here, each on its own line
    nginx['listen_port'] = 80
    nginx['listen_https'] = false

    registry_external_url 'https://registry.kliu.io'
    registry_nginx['listen_port'] = 81
    registry_nginx['listen_https'] = false

    gitlab_rails['smtp_enable'] = true;
    # Mailu connection
    gitlab_rails['smtp_address'] = 'kliu.io'
    gitlab_rails['smtp_port'] = 587
    gitlab_rails['smtp_user_name'] = 'gitlab@kliu.io'
    gitlab_rails['smtp_password'] = 'MqtU6PBB77gBr9Rk'
    gitlab_rails['smtp_domain'] = 'kliu.io'
    gitlab_rails['smtp_openssl_verify_mode'] = 'none'
    gitlab_rails['smtp_enable_starttls_auto'] = true
    gitlab_rails['gitlab_email_from'] = 'gitlab@kliu.io'
    gitlab_rails['gitlab_email_reply_to'] = 'noreply@kliu.io'

    gitlab_rails['omniauth_enabled'] = true

    # CAUTION!
    # This allows users to login without having a user account first. Define the allowed providers
    # using an array, e.g. ["saml", "twitter"], or as true/false to allow all providers or none.
    # User accounts will be created automatically when authentication was successful.
    gitlab_rails['omniauth_allow_single_sign_on'] = ['saml', 'twitter']
    gitlab_rails['omniauth_auto_link_ldap_user'] = true
    gitlab_rails['omniauth_block_auto_created_users'] = true

    gitlab_rails['omniauth_providers'] = [
      {
        "name" => "gitlab",
        "app_id" => ENV["APP_ID"],
        "app_secret" => ENV["APP_SECRET"],
        "args" => { "scope" => "api" }
      }
    ]
    gitlab_rails['time_zone'] = 'America/New_York'

    # Fix GitLab not picking up the real IP from Traefik
    nginx['real_ip_header'] = 'X-Forwarded-For'
    nginx['real_ip_recursive'] = 'on'