apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-hangouts
spec:
  selector:
    matchLabels:
      app: matrix-hangouts
  template:
    metadata:
      labels:
        app: matrix-hangouts
    spec:
      containers:
        - name: hangouts
          image: dock.mau.dev/tulir/mautrix-hangouts:latest
          volumeMounts:
            - name: config
              subPath: hangouts-registration.yaml
              mountPath: /data/registration.yaml
            - name: config
              subPath: hangouts-config.json
              mountPath: /data/config.yaml
            - name: data
              mountPath: /db
      volumes:
        - name: config
          secret:
            secretName: matrix2-config
        - name: data
          persistentVolumeClaim:
            claimName: matrix-hangouts-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matrix
  name: matrix-hangouts-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-hangouts
spec:
  selector:
    app: matrix-hangouts
  ports:
  - name: http
    targetPort: 8090
    port: 8090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: matrix-hangouts
spec:
  tls:
    - secretName: matrix-hangouts-tls
      hosts:
        - hg.kliu.io
  rules:
  - host: hg.kliu.io
    http:
      paths:
      - path: /login
        backend:
          serviceName: matrix-hangouts
          servicePort: 8090