apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-puppet-slack
spec:
  serviceName: matrix-puppet-slack
  selector:
    matchLabels:
      app: matrix-puppet-slack
  template:
    metadata:
      labels:
        app: matrix-puppet-slack
    spec:
      containers:
        - name: slack
          image: sorunome/mx-puppet-slack
          # Liveness probe: check if bot has an HTTPS connection to a server
          # (We assume this is the Slack API server)
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - netstat | grep -q ':https'
          volumeMounts:
            - name: config
              subPath: slack-registration.yaml
              mountPath: /data/slack-registration.yaml
            - name: config
              subPath: slack-config.yaml
              mountPath: /data/config.yaml
            - name: data
              mountPath: /data
      volumes:
        - name: config
          secret:
            secretName: matrix2-config
        - name: data
          persistentVolumeClaim:
            claimName: matrix-puppet-slack-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matrix
  name: matrix-puppet-slack-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-puppet-slack
spec:
  selector:
    app: matrix-puppet-slack
  ports:
    - name: http
      targetPort: 8432
      port: 8432
