apiVersion: v1
kind: Service
metadata:
  name: matrix2
spec:
  selector:
    app: matrix2
  ports:
    - name: http
      targetPort: 8008
      port: 8008
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix2
spec:
  serviceName: matrix2
  selector:
    matchLabels:
      app: matrix2
  template:
    metadata:
      labels:
        app: matrix2
        postgresql-client: "true"
    spec:
      containers:
        # Main matrix2 server
        - name: synapse
          image: matrixdotorg/synapse
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4G
          livenessProbe:
            httpGet:
              path: /_matrix/client/versions
              port: 8008
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /config/homeserver.yaml
          ports:
            - containerPort: 8008
              name: http
          volumeMounts:
            - name: config
              subPath: homeserver.yaml
              mountPath: /config/homeserver.yaml
            - name: config
              subPath: kliu.io.log.config
              mountPath: /config/kliu.io.log.config
            - name: config
              subPath: facebook-registration.yaml
              mountPath: /config/facebook-registration.yaml
            - name: config
              subPath: hangouts-registration.yaml
              mountPath: /config/hangouts-registration.yaml
            - name: config
              subPath: whatsapp-registration.yaml
              mountPath: /config/whatsapp-registration.yaml
            - name: config
              subPath: puppet-discord-registration.yaml
              mountPath: /config/puppet-discord-registration.yaml
            - name: data
              mountPath: /data
      volumes:
        # Stores SSL keys, media_store
        - name: data
          persistentVolumeClaim:
            claimName: matrix2-data
        - name: config
          secret:
            secretName: matrix2-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matrix2
  name: matrix2-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4000m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "14400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
  name: matrix2
spec:
  tls:
    - secretName: matrix2-tls
      hosts:
        - kliu.io
  rules:
    - host: kliu.io
      http:
        paths:
          - path: /_matrix/
            backend:
              serviceName: matrix2
              servicePort: 8008
          - path: /_synapse/
            backend:
              serviceName: matrix2
              servicePort: 8008
          - path: /.well-known/matrix/
            backend:
              serviceName: matrix2
              servicePort: 8008
