apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-whatsapp
spec:
  serviceName: matrix-whatsapp
  selector:
    matchLabels:
      app: matrix-whatsapp
  template:
    metadata:
      labels:
        app: matrix-whatsapp
    spec:
      containers:
        - name: whatsapp
          image: dock.mau.dev/tulir/mautrix-whatsapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: whatsapp
          volumeMounts:
            - name: config
              subPath: whatsapp-config.yaml
              mountPath: /data/config.yaml
            - name: config
              subPath: whatsapp-registration.yaml
              mountPath: /data/registration.yaml
            - name: data
              mountPath: /data
      volumes:
        - name: config
          secret:
            secretName: matrix2-config
        - name: data
          persistentVolumeClaim:
            claimName: matrix-whatsapp-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matrix-whatsapp
  name: matrix-whatsapp-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-whatsapp
spec:
  selector:
    app: matrix-whatsapp
  ports:
  - name: http
    targetPort: 8080
    port: 8080