apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-irc-hashbang
spec:
  selector:
    matchLabels:
      app: matrix-irc-hashbang
  template:
    metadata:
      labels:
        app: matrix-irc-hashbang
    spec:
      containers:
        - name: irc-hashbang
          args: [-c, config.yaml, -f, irc-hashbang-registration.yaml, -p, '9999']
          image: registry.potatofrom.space/kevin/matrix-appservice-irc
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              subPath: irc-hashbang-registration.yaml
              mountPath: /usr/src/app/irc-hashbang-registration.yaml
            - name: config
              subPath: irc-hashbang-config.yaml
              mountPath: /usr/src/app/config.yaml
            - name: data
              mountPath: /usr/src/app/data
      volumes:
        - name: config
          secret:
            secretName: matrix-config
        - name: data
          persistentVolumeClaim:
            claimName: matrix-irc-hashbang-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: matrix
  name: matrix-irc-hashbang-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-irc-hashbang
spec:
  selector:
    app: matrix-irc-hashbang
  ports:
  - name: http
    targetPort: 9999
    port: 9999
  - name: identd
    targetPort: 113
    port: 113
