apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-telegram
spec:
  selector:
    matchLabels:
      app: matrix-telegram
  template:
    metadata:
      labels:
        app: matrix-telegram
    spec:
      containers:
        - name: telegram
          image: dock.mau.dev/tulir/mautrix-telegram
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: telegram
          volumeMounts:
            - name: config
              subPath: telegram-registration.yaml
              mountPath: /data/registration.yaml
              # Telegram config is in PVC
            - name: data
              mountPath: /data
      volumes:
        - name: config
          secret:
            secretName: matrix-config
        - name: data
          persistentVolumeClaim:
            claimName: matrix-telegram-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: matrix-telegram
  name: matrix-telegram-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-telegram
spec:
  selector:
    app: matrix-telegram
  ports:
  - name: http
    targetPort: 8080
    port: 8080