apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matrix-facebook
spec:
  selector:
    matchLabels:
      app: matrix-facebook
  template:
    metadata:
      labels:
        app: matrix-facebook
    spec:
      containers:
        - name: facebook
          image: dock.mau.dev/tulir/mautrix-facebook
          volumeMounts:
            # config in PVC to avoid EROFS error
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matrix-facebook-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matrix-facebook
  name: matrix-facebook-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-facebook
spec:
  selector:
    app: matrix-facebook
  ports:
  - name: http
    targetPort: 8090
    port: 8090
