apiVersion: v1
kind: Service
metadata:
  name: riot
spec:
  selector:
    app: riot
  ports:
    - name: http
      targetPort: 80
      port: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: riot
spec:
  template:
    metadata:
      labels:
        app: riot
    spec:
      containers:
        - image: vectorim/riot-web:v1.4.0
          name: riot-web
          volumeMounts:
            - mountPath: /app/config.json
              name: config
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: riot-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: riot-config
  labels:
    app: riot
data:
  config.json: |
    {
        "default_hs_url": "https://potatofrom.space",
        "default_is_url": "https://vector.im",
        "brand": "Potatoriot",
        "integrations_ui_url": "https://dimension.potatofrom.space/riot",
        "integrations_rest_url": "https://dimension.potatofrom.space/api/v1/scalar",
        "integrations_widgets_urls": ["https://dimension.potatofrom.space/widgets"],
        "integrations_jitsi_widget_url": "https://dimension.potatofrom.space/widgets/jitsi",
        "features": {
            "feature_rich_quoting": "labs",
            "feature_pinning": "labs",
            "feature_presence_management": "labs",
            "feature_sticker_messages": "labs",
            "feature_jitsi": "labs",
            "feature_tag_panel": "enable",
            "feature_keybackup": "labs",
            "feature_custom_status": "labs",
            "feature_custom_tags": "labs",
            "feature_lazyloading": "enable",
            "feature_tabbed_settings": "labs",
            "feature_sas": "labs",
            "feature_room_breadcrumbs": "labs",
            "feature_state_counters": "labs",
            "feature_cider_composer": "labs",
            "feature_many_integration_managers": "labs"
        },
        "roomDirectory": {
            "servers": [
                "matrix.org"
            ]
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false
        },
        "terms_and_conditions_links": [
            {
                "url": "https://potatofrom.space/_matrix/consent",
                "text": "Privacy Policy"
            }
        ]
    }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: riot
spec:
  tls:
    - secretName: riot-tls
      hosts:
        - riot.potatofrom.space
  rules:
    - host: riot.potatofrom.space
      http:
        paths:
          - path: /
            backend:
              serviceName: riot
              servicePort: 80
