apiVersion: v1
kind: Service
metadata:
  name: riot
spec:
  selector:
    app: riot
  ports:
    - name: http
      targetPort: 80
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: riot
spec:
  selector:
    matchLabels:
      app: riot
  template:
    metadata:
      labels:
        app: riot
    spec:
      containers:
        - image: vectorim/riot-web:latest
          imagePullPolicy: Always
          name: riot-web
          volumeMounts:
            - mountPath: /app/config.json
              name: config
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: riot-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: riot-config
  labels:
    app: riot
data:
  config.json: |
    {
        "default_hs_url": "https://kliu.io",
        "default_is_url": "https://vector.im",
        "brand": "Potatoriot",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "integrations_widgets_urls": [
            "https://scalar.vector.im/_matrix/integrations/v1",
            "https://scalar.vector.im/api",
            "https://scalar-staging.vector.im/_matrix/integrations/v1",
            "https://scalar-staging.vector.im/api",
            "https://scalar-staging.riot.im/scalar/api"
        ],
        "features": {
        "feature_rich_quoting": "labs",
        "feature_pinning": "labs",
        "feature_presence_management": "labs",
        "feature_sticker_messages": "labs",
        "feature_jitsi": "labs",
        "feature_tag_panel": "enable",
        "feature_keybackup": "labs",
        "feature_custom_status": "labs",
        "feature_custom_tags": "labs",
        "feature_lazyloading": "enable",
        "feature_tabbed_settings": "labs",
        "feature_sas": "labs",
        "feature_room_breadcrumbs": "labs",
        "feature_state_counters": "labs",
        "feature_cider_composer": "labs",
        "feature_many_integration_managers": "labs"
    },
        "roomDirectory": {
            "servers": [
                "matrix.org"
            ]
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false
        },
        "terms_and_conditions_links": [
            {
                "url": "https://kliu.io/_matrix/consent",
                "text": "Privacy Policy"
            }
        ]
    }
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: riot
spec:
  tls:
    - secretName: riot-tls
      hosts:
        - riot.kliu.io
        - riot.potatofrom.space
  rules:
    - host: riot.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: riot
              servicePort: 80
    - host: riot.potatofrom.space
      http:
        paths:
          - path: /
            backend:
              serviceName: riot
              servicePort: 80
