apiVersion: v1
kind: Service
metadata:
  name: riot
spec:
  selector:
    app: riot
  ports:
  - name: http
    targetPort: 80
    port: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: riot
spec:
  template:
    metadata:
      labels:
        app: riot
    spec:
      containers:
        - image: registry.potatofrom.space/kevin/riot-web:latest
          name: riot-web
          resources: {}
          volumeMounts:
          - mountPath: /usr/share/nginx/html/config.json
            name: config
            subPath: config.json
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: riot-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: riot-config
  labels:
    app: riot
data:
  riot.im.conf: |
    -p 80
    -A 0.0.0.0
  config.json: |
    {
      "default_hs_url": "https://matrix.org",
      "default_is_url": "https://vector.im",
      "brand": "Potatoriot",
      "integrations_ui_url": "https://dimension.potatofrom.space/riot",
      "integrations_rest_url": "https://dimension.potatofrom.space/api/v1/scalar",
      "integrations_widgets_urls": ["https://dimension.potatofrom.space/widgets"],
      "integrations_jitsi_widget_url": "https://dimension.potatofrom.space/widgets/jitsi",
      "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
      "features": {
        "feature_rich_quoting": "labs",
        "feature_pinning": "labs",
        "feature_presence_management": "labs",
        "feature_sticker_messages": "labs",
        "feature_jitsi": "labs",
        "feature_tag_panel": "enable",
        "feature_keybackup": "labs",
        "feature_custom_status": "labs",
        "feature_custom_tags": "labs",
        "feature_lazyloading": "enable",
        "feature_tabbed_settings": "labs",
        "feature_sas": "labs",
        "feature_room_breadcrumbs": "labs",
        "feature_state_counters": "labs"
      },
      "roomDirectory": {
        "servers": [
            "matrix.org",
            "potatofrom.space"
        ]
      },
      "enable_presence_by_hs_url": {
        "https://matrix.org": false
      }
    }
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: riot
spec:
  tls:
    - secretName: riot-tls
      hosts:
        - riot.potatofrom.space
  rules:
  - host: riot.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: riot
          servicePort: 80
