apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    k8s-app: dl
  name: dl
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: dl
    spec:
      containers:
      - image: nginx
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: dl-files
        - mountPath: /etc/nginx/conf.d
          name: dl-config
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: dl-config
        persistentVolumeClaim:
          claimName: dl-claim0
      - name: dl-files
        hostPath:
          path: /mnt/storage/Kevin/Incoming
          type: Directory
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    k8s-app: dl
  name: dl
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    k8s-app: dl
status:
  loadBalancer: {}
