apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: geth
  name: geth
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: geth
    spec:
      containers:
      - args:
        - --cache
        - "1024"
        - --syncmode
        - fast
        - --rpc
        - --rpcaddr
        - 0.0.0.0
        - --rpccorsdomain
        - moz-extension://c73a460a-a578-4111-b320-8f3299cca995,chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
        image: ethereum/client-go:v1.8.4
        name: geth
        ports:
        - containerPort: 8545
        resources: {}
        volumeMounts:
        - mountPath: /root
          name: geth-data
      nodeSelector:
        kubernetes.io/hostname: otto
      restartPolicy: Always
      volumes:
      - name: geth-data
        persistentVolumeClaim:
          claimName: geth-data
status: {}
