apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    k8s-app: gitlab
  name: gitlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce:latest
        name: gitlab
        ports:
        - containerPort: 22
        resources: {}
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-claim0
        - mountPath: /var/opt/gitlab
          name: gitlab-claim1
      restartPolicy: Always
      volumes:
      - name: gitlab-claim0
        persistentVolumeClaim:
          claimName: gitlab-claim0
      - name: gitlab-claim1
        persistentVolumeClaim:
          claimName: gitlab-claim1
status: {}
