repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    values:
      - ./values/nginx-ingress.yaml
  - name: kubecfg
    namespace: default
    chart: ./kubecfg
    values:
      - ./values/kubecfg.yaml
      - ./values/kubecfg.secret.yaml