apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jackett
  name: jackett
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jackett
    spec:
      containers:
      - env:
        - name: PGID
          value: "100"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/New_York
        image: linuxserver/jackett
        name: jackett
        ports:
        - containerPort: 9117
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: jackett-claim0
      restartPolicy: Always
      volumes:
      - name: jackett-claim0
        persistentVolumeClaim:
          claimName: jackett-claim0
status: {}
