apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: matrix-synapse
  name: matrix-synapse
spec:
  ports:
  - name: "8448"
    port: 8448
    targetPort: 8448
  selector:
    io.kompose.service: matrix-synapse
status:
  loadBalancer: {}
