apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    k8s-app: portainer
  name: portainer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: portainer
    spec:
      containers:
      - image: portainer/portainer
        name: portainer
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: portainer-claim0
        - mountPath: /var/run/docker.sock
          name: portainer-claim1
      restartPolicy: Always
      volumes:
      - name: portainer-claim0
        persistentVolumeClaim:
          claimName: portainer-claim0
      - name: portainer-claim1
        persistentVolumeClaim:
          claimName: portainer-claim1
status: {}
