dependencies:
  - name: cert-manager
    version: 0.2.10
    repository: "@stable"
  - name: gitlab-omnibus
    version: 0.1.37
    repository: "@gitlab"
  - name: heapster
    version: 0.2.10
    repository: "@stable"
  - name: lamp
    version: 0.1.5
    repository: "@stable"
    alias: nextcloud
  - name: nginx-ingress
    version: 0.17.2
    repository: "@stable"
  - name: wordpress
    version: 1.0.5
    repository: "@stable"