apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "100"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/New_York
        image: linuxserver/sonarr
        name: sonarr
        ports:
        - containerPort: 8989
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: sonarr-claim0
        - mountPath: /tv
          name: sonarr-claim1
        - mountPath: /data
          name: sonarr-claim2
      restartPolicy: Always
      volumes:
      - name: sonarr-claim0
        persistentVolumeClaim:
          claimName: sonarr-claim0
      - name: sonarr-claim1
        persistentVolumeClaim:
          claimName: sonarr-claim1
      - name: sonarr-claim2
        persistentVolumeClaim:
          claimName: sonarr-claim2
status: {}
