# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "firewire_ohci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  
  boot.extraModulePackages = [ ];

  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/sda";

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "ext4";
    };
  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/5fd8e623-415d-4ea1-8c09-bd8daf9bace9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/cc4fe522-d718-45ea-8531-5c96d636812a";
      fsType = "ext4";
    };

  swapDevices = [ {
    device = "/swap";
    size = 4096;
  } ];
  
  nix.maxJobs = lib.mkDefault 4;
}
