# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "firewire_ohci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelPackages = pkgs.linuxPackages_4_19;
  boot.kernelParams = [ "scsi_mod.use_blk_mq=Y" ];
  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="sd*[!0-9]|sr*|nvme0n*", ATTR{queue/scheduler}="bfq"
  '';
  hardware.cpu.amd.updateMicrocode = true;
  
  boot.extraModulePackages = [ ];

  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/sda";

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "ext4";
    };
  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/5fd8e623-415d-4ea1-8c09-bd8daf9bace9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/cc4fe522-d718-45ea-8531-5c96d636812a";
      fsType = "ext4";
    };

  fileSystems."/mnt/250gb-netbook-hdd" = {
    device = "/dev/mapper/250gb-netbook-hdd";
    options = [ "errors=remount-ro" "noatime" "lazytime" "noexec" "nodev" ];
    encrypted = {
      enable = true;
      blkDev = "/dev/disk/by-uuid/58c60ce6-0ced-430f-b354-c2e1c46d6b74";
      keyFile = "/mnt-root/keys/keyfile-250gb-netbook-hdd.bin";
      label = "250gb-netbook-hdd";
    };
  };
  deployment.keys."keyfile-250gb-netbook-hdd.bin" = {
    permissions = "400";
    destDir = "/keys";
    keyFile = ../secrets/keys/keyfile-250gb-netbook-hdd.bin;
  };

  fileSystems."/mnt/150gb-dell-hdd" = {
    device = "/dev/mapper/150gb-dell-hdd";
    options = [ "errors=remount-ro" "noatime" "lazytime" "noexec" "nodev" ];
    encrypted = {
      enable = true;
      blkDev = "/dev/disk/by-uuid/4762f1cf-75bf-42b2-b39d-d8288c4509ad";
      keyFile = "/mnt-root/keys/keyfile-150gb-dell-hdd.bin";
      label = "150gb-dell-hdd";
    };
  };
  deployment.keys."keyfile-150gb-dell-hdd.bin" = {
    permissions = "400";
    destDir = "/keys";
    keyFile = ../secrets/keys/keyfile-150gb-dell-hdd.bin;
  };

  swapDevices = [ {
    device = "/swap";
    size = 4096;
  } ];
  zramSwap = {
    enable = true;
    memoryPercent = 100;
  };
  
  nix.maxJobs = lib.mkDefault 4;
}
