apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: nfs-client
provisioner: potatofrom.space/nfs-client # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  mountOptions: vers=4.2