- name: Install msmtp
  apt:
    name: msmtp
    state: present
- name: Copy msmtp config
  copy:
    src: ../files/msmtp.secret.conf
    dest: /etc/msmtprc
    mode: 0400
    owner: root
    group: root
- name: Copy email script
  copy:
    src: ../files/systemd-email
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
- name: Add systemd service
  copy:
    src: ../files/status-email-user@.service
    dest: /etc/systemd/system
    mode: 0644
    owner: root
    group: root