- name: Copy ddns.sh script
  copy:
    src: ddns.secret.sh
    dest: /usr/local/sbin/ddns.sh
    mode: 0755
- name: Create cron jobs to update DDNS
  cron:
    name: ddns
    minute: "*/5"
    job: "/bin/bash /usr/local/sbin/ddns.sh"
    state: present