apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: collabora-code
  name: collabora-code
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: collabora-code
    spec:
      containers:
      - image: collabora/code
        env:
          - name: domain
            value: {{ .Values.nextcloud.ingress.domain | replace "." "\\." | quote }}
        name: code
        securityContext:
          capabilities:
            add:
              - MKNOD
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: collabora-code
  name: collabora-code
spec:
  ports:
  - name: http
    port: 9980
    targetPort: 9980
  selector:
    app: collabora-code
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/server-snippet: "proxy_ssl_verify off;"
    kubernetes.io/tls-acme: 'true'
  name: collabora-code
spec:
  tls:
    - secretName: collabora-code-tls
      hosts:
        - office.potatofrom.space
  rules:
  - host: office.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: collabora-code
          servicePort: 9980