apiVersion: v1
kind: Service
metadata:
  name: godns
spec:
  selector:
    app: godns
  ports:
  - name: http
    targetPort: 80
    port: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: godns
spec:
  template:
    metadata:
      labels:
        app: godns
    spec:
      containers:
        - image: timothyye/godns:1.5.2
          name: godns
          resources: {}
          volumeMounts:
          - mountPath: /usr/local/godns/config.json
            name: config
            subPath: config.json
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: godns-config