kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mailserver
  labels:
    app: mailserver
spec:
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: rem
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      containers:
        - name: mailserver
          image: tvial/docker-mailserver:release-v6.0.0
          ports:
            - name: smtp
              containerPort: 25
            - name: imap
              containerPort: 143
            - name: smtp-auth
              containerPort: 587
            - name: imap-secure
              containerPort: 993
          env:
            - name: ENABLE_CLAMAV
              value: '1'
            - name: ENABLE_SPAMASSASSIN
              value: '1'
            - name: OVERRIDE_HOSTNAME
              value: mail.potatofrom.space
            - name: SSL_TYPE
              value: 'manual'
            - name: SSL_CERT_PATH
              value: '/etc/ssl/mailserver/tls.crt'
            - name: SSL_KEY_PATH
              value: '/etc/ssl/mailserver/tls.key'
            - name: ONE_DIR
              value: '1'
            - name: TLS_LEVEL
              value: intermediate # TLS v1-1.2 + broad compatibility
              # Required for Nextcloud compatibility
          envFrom:
            - secretRef:
                name: mailserver.mailgun-relayhost
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_PTRACE
          volumeMounts:
            - name: config
              subPath: postfix-accounts.cf
              mountPath: /tmp/docker-mailserver/postfix-accounts.cf
              readOnly: true
            - name: config
              subPath: postfix-main.cf
              mountPath: /tmp/docker-mailserver/postfix-main.cf
              readOnly: true
            - name: config
              subPath: postfix-virtual.cf
              mountPath: /tmp/docker-mailserver/postfix-virtual.cf
              readOnly: true
            - name: config
              subPath: SigningTable
              mountPath: /tmp/docker-mailserver/opendkim/SigningTable
              readOnly: true
            - name: config
              subPath: KeyTable
              mountPath: /tmp/docker-mailserver/opendkim/KeyTable
              readOnly: true
            - name: config
              subPath: TrustedHosts
              mountPath: /tmp/docker-mailserver/opendkim/TrustedHosts
              readOnly: true
            - name: opendkim-keys
              mountPath: /tmp/docker-mailserver/opendkim/keys
              readOnly: true
            - name: data
              mountPath: /var/mail
            - name: state
              mountPath: /var/mail-state
            - name: tls
              mountPath: /etc/ssl/mailserver
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mailserver.config
        - name: opendkim-keys
          secret:
            secretName: mailserver.opendkim.keys
        - name: data
          persistentVolumeClaim:
            claimName: mailserver-data-claim
        - name: state
          persistentVolumeClaim:
            claimName: mailserver-state
        - name: tls
          secret:
            secretName: mailserver.tls
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: mailserver
  name: mailserver-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: mailserver
  name: mailserver-state
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: mailserver
  labels:
    app: mailserver
  annotations:
    kubernetes.io/tls-acme: 'true'
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: default-backend
              servicePort: 80
  tls:
    - secretName: mailserver.tls
      hosts:
        - potatofrom.space
