apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft
    targetPort: 25565
    port: 25565
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
spec:
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            # Accept Mojang EULA (required)
            - name: EULA
              value: "TRUE"
            # Set Minecraft version and opts
            - name: TYPE
              value: FORGE
            - name: FORGEVERSION
              value: "14.23.3.2707"
            - name: VERSION
              value: "1.12.2"
            - name: MEMORY
              value: 4G
            # Minecraft config
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: DIFFICULTY
              value: hard
            - name: LEVEL_TYPE
              value: quark_realistic
            - name: OPS
              value: GCat,Ajaxi,dardahar
            - name: ENABLE_QUERY
              value: "TRUE"
            - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
              value: "TRUE"
            - name: MOTD
              value: "Saucymods — SevTech: Ages"
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - name: data
              mountPath: /data
            - name: backups
              mountPath: /backups
          # Allow for attaching
          tty: true
          stdin: true
      nodeSelector:
        kubernetes.io/hostname: rem
      hostNetwork: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data
        - name: backups
          hostPath:
            path: /mnt/storage/Kevin/Backups/Minecraft/Current
            type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: minecraft
  name: minecraft-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
