apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: parity
  name: parity
spec:
  selector:
    matchLabels:
      app: parity
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: parity
    spec:
      containers:
      - image: parity/parity:nightly
        imagePullPolicy: Always
        args: [-d, /data, --jsonrpc-interface=all, --jsonrpc-cors=*, --jsonrpc-apis=safe, --no-ancient-blocks, --cache=1024, --snapshot-peers=50, --peers=50, --warp-barrier=5720000]
        name: parity
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: parity-data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: parity
  name: parity-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: parity
  name: parity
spec:
  ports:
  - name: jsonrpc
    port: 8545
    targetPort: 8545
  selector:
    app: parity
---
