apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: parity
  name: parity
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: parity
    spec:
      containers:
      - image: parity/parity:beta
        args: [-d, /data, --jsonrpc-interface, all, --jsonrpc-cors, '*', --jsonrpc-apis, safe, --no-ancient-blocks, --cache=2048]
        name: parity
        resources:
          requests:
            cpu: 1000m
            memory: 750Mi
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: parity-data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: parity
  name: parity-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: parity
  name: parity
spec:
  ports:
  - name: jsonrpc
    port: 8545
    targetPort: 8545
  selector:
    app: parity
---
