apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tor
  name: tor
spec:
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: rem
      containers:
      - image: jess/tor-relay
        command: [tor]
        args: [-f, /etc/tor/torrc]
        name: tor
        resources: {}
        volumeMounts:
        - mountPath: /etc/tor/torrc
          name: config
          subPath: torrc
          readOnly: true
        - mountPath: /var/lib/tor/.tor
          name: data
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: tor-config
      - name: data
        persistentVolumeClaim:
          claimName: tor-data
status: {}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tor-config
  labels:
    app: tor
data:
  torrc: |
    ORPort 9001
    DirPort 9030
    Address potatofrom.space
    ## A handle for your relay, so people don't have to refer to it by key.
    Nickname potatorelay
    ContactInfo 8792E2260F507DA00F0DB58E2160C3EB40A944EC Kevin Liu kevin@potatofrom.space
    ExitPolicy reject *:*
    RelayBandwidthRate 10 MBytes
    RelayBandwidthBurst 20 MBytes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: tor
  name: tor-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}