{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-web-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.domain }}
    secretName: {{ template "fullname" . }}-web
  {{- end }}
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}-web
          servicePort: web
{{- end }}