- name: Enable TCP BBR
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: "net.core.default_qdisc", value: "fq" }
    - { name: "net.ipv4.tcp_congestion_control", value: "bbr" }
