
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-nfs-provisioner-nfs-server-provisioner-0
  labels:
    type: local
spec:
  claimRef:
    namespace: kube-system
    name: data-nfs-provisioner-nfs-server-provisioner-0
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/kubes"
