---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: nfs-provisioner
  namespace: kube-system
  labels:
    chart: nfs-server-provisioner
spec:
  chartGitPath: nfs-server-provisioner
  releaseName: nfs-provisioner
  values:
    nodeSelector:
      kubernetes.io/hostname: rem
    persistence:
      enabled: true
      storageClass: "-"
      size: 200Gi
    storageClass:
      defaultClass: true