apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: archiveteam-warrior
  name: archiveteam-warrior
spec:
  selector:
    matchLabels:
      app: archiveteam-warrior
  template:
    metadata:
      labels:
        app: archiveteam-warrior
    spec:
      nodeSelector:
        kubernetes.io/hostname: rem
      containers:
        - image: archiveteam/warrior-dockerfile
          name: archiveteam-warrior
          env:
            - name: DOWNLOADER
              value: Pneumaticat
            - name: SELECTED_PROJECT
              value: tumblr
            - name: CONCURRENT_ITEMS
              value: "20"
          ports:
            - containerPort: 8001
              name: http
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 240
      restartPolicy: Always
status: {}