apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: archiveteam-warrior
  name: archiveteam-warrior
spec:
  serviceName: archiveteam-warrior
  selector:
    matchLabels:
      app: archiveteam-warrior
  template:
    metadata:
      labels:
        app: archiveteam-warrior
    spec:
      containers:
        - image: archiveteam/warrior-dockerfile
          name: archiveteam-warrior
          env:
            - name: DOWNLOADER
              value: Pneumaticat
            - name: SELECTED_PROJECT
              value: auto
            - name: CONCURRENT_ITEMS
              value: "6"
          ports:
            - containerPort: 8001
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 240