apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bitwarden
  name: bitwarden
spec:
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
        - image: bitwardenrs/server:1.13.0
          name: bitwarden
          env:
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: DOMAIN
              value: https://pw.kliu.io
          livenessProbe:
            httpGet:
              path: /
              port: 80
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bitwarden-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitwarden
  name: bitwarden
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: websocket
      protocol: TCP
      port: 3012
      targetPort: 3012
  selector:
    app: bitwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bitwarden
  name: bitwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: bitwarden
spec:
  tls:
    - secretName: bitwarden-tls
      hosts:
        - pw.kliu.io
  rules:
    - host: pw.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: bitwarden
              servicePort: 80
          - path: /notifications/hub
            backend:
              serviceName: bitwarden
              servicePort: 3012
