apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog
    spec:
      containers:
      - image: registry.potatofrom.space/kevin/potatofrom.space
        name: blog
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: blog
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: blog
spec:
  tls:
    - secretName: blog-tls
      hosts:
        - blog.potatofrom.space
        - www.potatofrom.space
        - potatofrom.space
  rules:
  - host: blog.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 80
  - host: www.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 80
  - host: potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 80