apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boinc-amd
  labels:
    app: boinc-amd
spec:
  selector:
    matchLabels:
      name: boinc-amd
  template:
    metadata:
      labels:
        name: boinc-amd
    spec:
      hostNetwork: true
      containers:
      - name: boinc-amd
        env:
          - name: BOINC_CMD_LINE_OPTIONS
            value: "--allow_remote_gui_rpc"
          - name: BOINC_GUI_RPC_PASSWORD
            value: {{ .Values.boinc_amd.password | quote }}
        image: pneumaticat/boinc
        resources:
          limits:
            amd.com/gpu: 1
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /var/lib/boinc-client
          name: data
        restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: boinc-amd-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: boinc-amd
  name: boinc-amd-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
