kind: Service
apiVersion: v1
metadata:
  name: calibre
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
---
kind: Endpoints
apiVersion: v1
metadata:
  name: calibre
subsets:
  - addresses:
    - ip: 192.168.1.5
    ports:
    - protocol: TCP
      port: 8080
      name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: calibre-web
spec:
  tls:
    - secretName: calibre-web-tls
      hosts:
        - books.kliu.io
  rules:
  - host: books.kliu.io
    http:
      paths:
      - path: /
        backend:
          serviceName: calibre
          servicePort: 8080