apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: calibre-web
  name: calibre-web
spec:
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
      - image: linuxserver/calibre-web
        name: calibre-web
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /books
          name: books
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: calibre-web-config
      - name: books
        hostPath:
          path: /mnt/storage/Kevin/Literature/eBooks
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calibre-web
  name: calibre-web
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app: calibre-web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: calibre-web
  name: calibre-web-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: calibre-web
spec:
  tls:
    - secretName: calibre-web-tls
      hosts:
        - books.potatofrom.space
  rules:
  - host: books.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: calibre-web
          servicePort: 8083