apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: commento-db
spec:
  serviceName: commento-db
  selector:
    matchLabels:
      app: commento-db
  template:
    metadata:
      labels:
        app: commento-db
    spec:
      containers:
        - name: db
          image: postgres:11-alpine
          env:
            - name: POSTGRES_DB
              value: commento
            - name: POSTGRES_USER
              value: commento
            - name: POSTGRES_PASSWORD
              value: {{ .Values.commento.db.password | quote }}
          ports:
            - containerPort: 5342
              name: postgres
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: commento-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: commento
  name: commento-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: commento-db
spec:
  selector:
    app: commento-db
  ports:
  - name: postgres
    targetPort: 5432
    port: 5432