apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: covid-survival
  name: covid-survival
spec:
  selector:
    matchLabels:
      app: covid-survival
  replicas: 2
  template:
    metadata:
      labels:
        app: covid-survival
    spec:
      containers:
        - image: php:apache
          name: covid-survival
          volumeMounts:
            - mountPath: /var/www/html
              name: files
      restartPolicy: Always
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: covid-survival-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: covid-survival
  name: covid-survival
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: covid-survival
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: covid-survival
  name: covid-survival-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: covid-survival
spec:
  tls:
    - secretName: covid-survival-tls
      hosts:
        - covidsurvival.guide
  rules:
    - host: covidsurvival.guide
      http:
        paths:
          - path: /
            backend:
              serviceName: covid-survival
              servicePort: 80