apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: emby
  name: emby
spec:
  serviceName: emby
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
        - image: jellyfin/jellyfin:nightly-20200529
          imagePullPolicy: Always
          name: emby
          ports:
            - containerPort: 8096
              name: http
          resources: {}
          livenessProbe:
            httpGet:
              path: /web/index.html
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 3
          volumeMounts:
            - mountPath: /data/tv-shows
              name: tv
              readOnly: true
            - mountPath: /data/movies
              name: movies
              readOnly: true
            - mountPath: /data/music
              name: music
              readOnly: true
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: emby-config
        - name: tv
          hostPath:
            path: /mnt/storage/Kevin/Videos/TV Shows
        - name: movies
          hostPath:
            path: /mnt/storage/Kevin/Videos/Movies
        - name: music
          hostPath:
            path: /mnt/storage/Kevin/Audio/Music
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: emby
  name: emby
spec:
  ports:
    - name: http
      port: 8096
      targetPort: http
  selector:
    app: emby
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: emby
  name: emby-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: emby
spec:
  tls:
    - secretName: emby-tls
      hosts:
        - media.kliu.io
  rules:
    - host: media.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: emby
              servicePort: 8096
