apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: emby
  name: emby
spec:
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emby
    spec:
      containers:
        - image: nvllsvm/emby-unlocked:3.5.0.0
          env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "1000"
          name: emby
          ports:
            - containerPort: 8096
              name: http
          resources: {}
          livenessProbe:
            httpGet:
              path: /web/index.html
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 3
          volumeMounts:
            - mountPath: /data/tv-shows
              name: tv
              readOnly: true
            - mountPath: /data/movies
              name: movies
              readOnly: true
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: emby-config
        - name: tv
          nfs:
            path: /storage/Kevin/Videos/TV Shows
            server: 192.168.1.5
        - name: movies
          nfs:
            path: /storage/Kevin/Videos/Movies
            type: 192.168.1.5
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: emby
  name: emby
spec:
  ports:
    - name: http
      port: 8096
      targetPort: http
  selector:
    app: emby
---
kind: PersistentVolumeClaim
metadata:
  labels:
    app: emby
  name: emby-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: emby
spec:
  tls:
    - secretName: emby-tls
      hosts:
        - media.potatofrom.space
  rules:
    - host: media.potatofrom.space
      http:
        paths:
          - path: /
            backend:
              serviceName: emby
              servicePort: 8096
