apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ethminer
  labels:
    app: ethminer
spec:
  serviceName: ethminer
  selector:
    matchLabels:
      name: ethminer
  template:
    metadata:
      labels:
        name: ethminer
    spec:
      containers:
      - name: ethminer
        image: cryptojunkies/claymore:eth-amd-latest
        args: [-epool, "eth-us-east1.nanopool.org:9999", -ewal, 0xA0fd60A944c1f86D529EEbEf19b34ca61294Ffe5/rem/kevin@kliu.io, -epsw, x]
        resources:
          limits:
            amd.com/gpu: 1
