apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hnsminer
  labels:
    app: hnsminer
spec:
  serviceName: hnsminer
  selector:
    matchLabels:
      name: hnsminer
  template:
    metadata:
      labels:
        name: hnsminer
    spec:
      containers:
      - name: hnsminer
        image: pneumaticat/hnsminer
        resources:
          limits:
            amd.com/gpu: 1
        volumeMounts:
          - name: config
            mountPath: /app/HandyMiner-CLI/config.json
            subPath: config.json
      volumes:
      - name: config
        configMap:
          name: hnsminer-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hnsminer-config
data:
  config.json: |
    {
      "gpus": "0",
      "gpu_platform": "",
      "gpu_mfg": "unikern",
      "intensity": 11,
      "host": "handshake.6block.com",
      "port": 7701,
      "stratum_user": "testtest.1",
      "stratum_pass": "123",
      "mode": "pool",
      "poolDifficulty": 100,
      "muteWinningFanfare": true
    }