apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invidious
  name: invidious
spec:
  selector:
    matchLabels:
      app: invidious
      postgresql-client: "true"
  replicas: 1
  template:
    metadata:
      labels:
        app: invidious
        postgresql-client: "true"
    spec:
      containers:
        - image: 1337kavin/invidious
          envFrom:
          - secretRef:
              name: invidious-config
          name: invidious
          resources:
            limits:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invidious
  name: invidious
  name: invidious
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: invidious
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: invidious
spec:
  tls:
    - secretName: invidious-tls
      hosts:
        - v.kliu.io
  rules:
    - host: v.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: invidious
              servicePort: http