apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kevinliu
  name: kevinliu
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kevinliu
    spec:
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: config
              subPath: index.html
      volumes:
        - name: config
          configMap:
            name: kevinliu-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kevinliu
  name: kevinliu
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: kevinliu
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: kevinliu
spec:
  tls:
    - secretName: kevinliu-tls
      hosts:
        - kevinliu.ml
        - www.kevinliu.ml
  rules:
    - host: kevinliu.ml
      http:
        paths:
          - path: /
            backend:
              serviceName: kevinliu
              servicePort: http
    - host: www.kevinliu.ml
      http:
        paths:
          - path: /
            backend:
              serviceName: kevinliu
              servicePort: http
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kevinliu-config
  labels:
    app: kevinliu
data:
  index.html: |
    <!DOCTYPE html>
    <html>

      <head>
        <meta charset="utf-8">
        <title>kevinliu</title>

        <style>
          html,
          body {
            color: #c5efcb;
            background-color: #020402;
            font-family: sans-serif;

            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
            width: 100%;
          }
          
          a {
            color: #c5efcb;
            background-color: #020402;
          }
        </style>
        <!-- Matomo -->
        <script type="text/javascript">
          var _paq = window._paq || [];
          /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
            var u="https://matomo.potatofrom.space/";
            _paq.push(['setTrackerUrl', u+'matomo.php']);
            _paq.push(['setSiteId', '5']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
          })();
        </script>
        <!-- End Matomo Code -->
      </head>

      <body>
        <div>
          <h1>
            Kevin Liu
          </h1>
          <p>
            <a href="mailto:me@kevinliu.ml">email me</a>
          </p>
        </div>
      </body>

    </html>