apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://kliu.io
    kubernetes.io/tls-acme: "true"
  name: kevinliu
spec:
  tls:
    - secretName: kevinliu-tls
      hosts:
        - kevinliu.ml
        - www.kevinliu.ml
  rules:
    - host: kevinliu.ml
      http:
        paths:
          - path: /
            backend:
              serviceName: default-backend
              servicePort: 80
    - host: www.kevinliu.ml
      http:
        paths:
          - path: /
            backend:
              serviceName: default-backend
              servicePort: 80