apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: matomo
  name: matomo
spec:
  serviceName: matomo
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
        - image: matomo:3.13.4
          env:
            - name: MYSQL_USER
              value: matomo
            - name: MYSQL_DATABASE_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              value: matomo
            - name: MYSQL_PASSWORD
              value: {{ .Values.matomo.password }}
          name: matomo
          volumeMounts:
            - mountPath: /var/www/html
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matomo-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matomo
  name: matomo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: matomo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matomo
  name: matomo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: matomo
spec:
  tls:
    - secretName: matomo-tls
      hosts:
        - matomo.kliu.io
  rules:
    - host: matomo.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: matomo
              servicePort: 80
