apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: monica
  name: monica
spec:
  selector:
    matchLabels:
      app: monica
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monica
    spec:
      containers:
        - image: pneumaticat/monica
          envFrom:
            - secretRef:
                name: monica-secret
          name: monica
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /var/www/monica/storage
              name: data
        - name: db
          env:
            - name: MYSQL_DATABASE
              value: monica
            - name: MYSQL_USER
              value: {{ .Values.monica.db.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.monica.db.password | quote }}
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
          image: mariadb
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: monica-db
        - name: data
          persistentVolumeClaim:
            claimName: monica-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monica
  name: monica
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: monica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: monica
  name: monica-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: monica
  name: monica-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: monica
spec:
  tls:
    - secretName: monica-tls
      hosts:
        - monica.potatofrom.space
  rules:
    - host: monica.potatofrom.space
      http:
        paths:
          - path: /
            backend:
              serviceName: monica
              servicePort: 80
