apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  serviceName: nextcloud
  selector:
    matchLabels:
      app: nextcloud
      postgresql-client: "true"
  template:
    metadata:
      labels:
        app: nextcloud
        postgresql-client: "true"
    spec:
      containers:
        - image: nextcloud
          name: nextcloud
          volumeMounts:
            - mountPath: /var/www/html
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collabora-code
  name: collabora-code
spec:
  selector:
    matchLabels:
      app: collabora-code
  template:
    metadata:
      labels:
        app: collabora-code
    spec:
      containers:
        - image: collabora/code
          name: code
          env:
          - name: domain
            value: cloud\.kliu\.io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nextcloud
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: collabora-code
  name: collabora-code
spec:
  ports:
    - name: http
      port: 9980
      targetPort: 9980
  selector:
    app: collabora-code
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
  name: nextcloud
spec:
  tls:
    - secretName: nextcloud-tls
      hosts:
        - cloud.kliu.io
        - office.kliu.io
  rules:
    - host: cloud.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: nextcloud
              servicePort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: collabora-code
spec:
  tls:
    - secretName: nextcloud-tls
      hosts:
        - cloud.kliu.io
        - office.kliu.io
  rules:
    - host: office.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: collabora-code
              servicePort: http
