apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: geth
  name: geth
spec:
  serviceName: geth
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: rem
      containers:
      - image: ethereum/client-go
        name: geth
        volumeMounts:
        - mountPath: /root
          name: data
      volumes:
      - name: data
        hostPath:
          path: /var/lib/geth