apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: parity
  name: parity
spec:
  selector:
    matchLabels:
      app: parity
  template:
    metadata:
      labels:
        app: parity
    spec:
      nodeSelector:
        kubernetes.io/hostname: rem
      hostNetwork: true
      containers:
      - image: parity/parity:v2.0.6
        imagePullPolicy: Always
        args: [-d, /data, --jsonrpc-interface=all, --jsonrpc-cors=*,
              --jsonrpc-apis=safe, --no-ancient-blocks,--chain=kovan]
        name: parity
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: parity-data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: parity
  name: parity-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
