apiVersion: v1
kind: Service
metadata:
  name: proxmox
spec:
  type: ExternalName
  externalName: karmaxer.i.kliu.io
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: proxmox
spec:
  tls:
    - secretName: proxmox-tls
      hosts:
        - proxmox.kliu.io
  rules:
    - host: proxmox.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: proxmox
              servicePort: 8006