apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: red-discord-bot
  name: red-discord-bot
spec:
  serviceName: red-discord-bot
  selector:
    matchLabels:
      app: red-discord-bot
  template:
    metadata:
      labels:
        app: red-discord-bot
    spec:
      containers:
        - image: phasecorex/red-discordbot
          name: red-discord-bot
          envFrom:
          - secretRef:
              name: red-discord-bot-secret
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: red-discord-bot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: red-discord-bot
  name: red-discord-bot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi