apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: retro
  name: retro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: retro
    spec:
      containers:
        - image: pneumaticat/retro
          name: retro
          volumeMounts:
            - mountPath: /var/www/html
              name: files
      restartPolicy: Always
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: retro-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: retro
  name: retro
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: retro
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: retro
  name: retro-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: retro
spec:
  tls:
    - secretName: retro-tls
      hosts:
        - retro.kliu.io
  rules:
    - host: retro.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: retro
              servicePort: 80