apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: roundcube
  name: roundcube
spec:
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - image: roundcube/roundcubemail
          name: roundcube
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: potatofrom.space
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: potatofrom.space
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /var/www/html
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: roundcube-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: roundcube
  name: roundcube
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: roundcube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: roundcube
  name: roundcube-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: roundcube
spec:
  tls:
    - secretName: roundcube-tls
      hosts:
        - mail.potatofrom.space
  rules:
    - host: mail.potatofrom.space
      http:
        paths:
          - path: /
            backend:
              serviceName: roundcube
              servicePort: 80
