apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: shinobi
  name: shinobi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shinobi
    spec:
      nodeSelector:
        kubernetes.io/hostname: rem
      containers:
      - args: [node, /opt/shinobi/camera.js]
        image: registry.gitlab.com/pneumaticat/shinobidocker:latest
        name: shinobi
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /opt/shinobi/videos
          name: data
        - mountPath: /var/lib/mysql
          name: database
        - mountPath: /run
          name: socket
      - args: [node, /opt/shinobi/cron.js]
        image: registry.gitlab.com/pneumaticat/shinobidocker:latest
        name: cron
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /opt/shinobi/videos
          name: data
        - mountPath: /run
          name: socket
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: shinobi-config
      - name: data
        hostPath:
          path: /mnt/storage/Kevin/Computing/Data/Shinobi
          type: Directory
      - name: database
        persistentVolumeClaim:
          claimName: shinobi-database
      - name: socket
        emptyDir: {}
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: shinobi
  name: shinobi-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: shinobi
  name: shinobi-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shinobi
  name: shinobi
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: shinobi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: shinobi-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Shinobi"
    kubernetes.io/tls-acme: 'true'
  name: shinobi
spec:
  tls:
    - secretName: shinobi-tls
      hosts:
        - zm.potatofrom.space
  rules:
  - host: zm.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: shinobi
          servicePort: 8080