apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tiddlywiki
  name: tiddlywiki
spec:
  selector:
    matchLabels:
      app: tiddlywiki
  template:
    metadata:
      labels:
        app: tiddlywiki
    spec:
      containers:
      - image: mazzolino/tiddlywiki
        env:
          - name: USERNAME
            value: kevin
          - name: PASSWORD
            value: {{ .Values.tiddlywiki.password | quote }}
        name: tiddlywiki
        volumeMounts:
        - mountPath: /var/lib/tiddlywiki
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tiddlywiki-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tiddlywiki
  name: tiddlywiki-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tiddlywiki
  name: tiddlywiki
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: tiddlywiki
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: tiddlywiki
spec:
  tls:
    - secretName: tiddlywiki-tls
      hosts:
        - wiki.potatofrom.space
  rules:
    - host: wiki.potatofrom.space
      http:
        paths:
          - path: /
            backend:
              serviceName: tiddlywiki
              servicePort: http