apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tor
spec:
  serviceName: tor
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      hostNetwork: true
      containers:
        - name: tor
          image: jess/tor-relay
          command: [tor]
          args: [-f, /etc/tor/torrc.middle2]
          env:
          - name: RELAY_NICKNAME
            value: potatorelay
          - name: CONTACT_NAME
            value: Kevin Liu
          - name: CONTACT_EMAIL
            value: kevin@kliu.io
          - name: RELAY_BANDWIDTH_RATE
            value: "8 MBytes"
          - name: RELAY_BANDWIDTH_BURST
            value: "8 MBytes"
          volumeMounts:
            - name: data
              mountPath: /var/lib/tor/.tor
            - name: config
              mountPath: /etc/tor/torrc.middle2
              subPath: torrc
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tor-data
        - name: config
          configMap:
            name: tor-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tor
  name: tor-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 250Mi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tor-config
  labels:
    app: tor
data:
  torrc: |
    ORPort 32972
    DirPort 32973
    ## A handle for your relay, so people don't have to refer to it by key.
    Nickname potatorelay3
    ContactInfo Kevin Liu <kevin@kliu.io>
    ExitPolicy reject *:*