apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tor
  name: tor
spec:
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      containers:
        - image: registry.potatofrom.space/kevin/pia-tor:latest
          name: tor
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - MKNOD
          volumeMounts:
            - mountPath: /etc/tor/torrc
              name: config
              subPath: torrc
            - mountPath: /auth.conf
              name: config
              subPath: auth.conf
              readOnly: true
            - mountPath: /var/lib/tor/
              name: data
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: tor-config
        - name: data
          persistentVolumeClaim:
            claimName: tor-data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: tor
  name: tor-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
