kind: Service
apiVersion: v1
metadata:
  name: transmission
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9091
    name: http
---
kind: Endpoints
apiVersion: v1
metadata:
  name: transmission
subsets:
  - addresses:
    - ip: 192.168.1.17
    ports:
    - protocol: TCP
      port: 9091
      name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4000m
  name: transmission
spec:
  tls:
    - secretName: transmission-tls
      hosts:
        - transmission.kliu.io
  rules:
    - host: transmission.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: transmission
              servicePort: http