apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: transmission
  name: transmission
spec:
  serviceName: transmission
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      nodeSelector:
        kubernetes.io/hostname: rem
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: TRANSMISSION_RATIO_LIMIT_ENABLED
              value: "false"
            - name: LOCAL_NETWORK
              value: 192.168.0.0/16
            - name: OPENVPN_PROVIDER
              value: CUSTOM
            - name: OPENVPN_USERNAME
              value: vpn
            - name: OPENVPN_PASSWORD
              value: vpn
          image: haugene/transmission-openvpn:latest
          name: transmission
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data/completed
              name: completed
            - mountPath: /data/incomplete
              name: incomplete
            - mountPath: /data/transmission-home
              name: data
            - mountPath: /etc/openvpn/custom/default.ovpn
              name: data
              subPath: default.ovpn
      restartPolicy: Always
      volumes:
        - name: completed
          hostPath:
            path: /mnt/storage/Kevin/Incoming/completed
        - name: incomplete
          hostPath:
            path: /mnt/storage/Kevin/Incoming/incomplete
        - name: data
          persistentVolumeClaim:
            claimName: transmission-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission
  name: transmission
spec:
  ports:
    - name: http
      port: 9091
      targetPort: 9091
  selector:
    app: transmission
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: transmission
  name: transmission-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: transmission-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - transmission"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4000m
  name: transmission
spec:
  tls:
    - secretName: transmission-tls
      hosts:
        - transmission.kliu.io
  rules:
    - host: transmission.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: transmission
              servicePort: 9091
