kind: Service
apiVersion: v1
metadata:
  name: transmission
spec:
  type: ExternalName
  externalName: transmission.i.kliu.io
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4000m
  name: transmission
spec:
  tls:
    - secretName: transmission-tls
      hosts:
        - transmission.kliu.io
  rules:
    - host: transmission.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: transmission
              servicePort: 9091