apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zoneminder
  name: zoneminder
spec:
  selector:
    matchLabels:
      app: zoneminder
  template:
    metadata:
      labels:
        app: zoneminder
    spec:
      containers:
      - image: zoneminderhq/zoneminder:latest-ubuntu18.04
        imagePullPolicy: Always
        name: zoneminder
        livenessProbe:
          httpGet:
            path: /zm/
            port: 80
          initialDelaySeconds: 60
        volumeMounts:
        - mountPath: /var/cache/zoneminder/images
          subPath: images
          name: vids
        - mountPath: /var/cache/zoneminder/events
          subPath: events
          name: vids
        - mountPath: /var/lib/mysql
          name: data
        - mountPath: /dev/shm
          name: shm
      restartPolicy: Always
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
      - name: vids
        hostPath:
          path: /mnt/storage/Kevin/Computing/Data/Zoneminder
          type: Directory
      - name: data
        persistentVolumeClaim:
          claimName: zoneminder-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: zoneminder
  name: zoneminder-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zoneminder
  name: zoneminder
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: zoneminder
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: zoneminder-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - zoneminder"
  name: zoneminder
spec:
  tls:
    - secretName: zoneminder-tls
      hosts:
        - zm.potatofrom.space
  rules:
  - host: zm.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: zoneminder
          servicePort: http