apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zoneminder
  name: zoneminder
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zoneminder
    spec:
      containers:
      - image: dlandon/zoneminder
        name: zoneminder
        securityContext:
          privileged: true
        env:
          - name: SHMMAX
            value: "50%"
          - name: TZ
            value: America/New_York
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /var/cache/zoneminder
          name: vids
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: zoneminder-config
      - name: vids
        hostPath:
          path: /mnt/storage/Kevin/Computing/Data/Zoneminder
          type: Directory
      - name: data
        persistentVolumeClaim:
          claimName: zoneminder-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: zoneminder
  name: zoneminder-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: zoneminder
  name: zoneminder-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zoneminder
  name: zoneminder
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: zoneminder
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: zoneminder-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - zoneminder"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: zoneminder
spec:
  tls:
    - secretName: zoneminder-tls
      hosts:
        - zm.potatofrom.space
  rules:
  - host: zm.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: zoneminder
          servicePort: 443