apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zoneminder
  name: zoneminder
spec:
  selector:
    matchLabels:
      app: zoneminder
  template:
    metadata:
      labels:
        app: zoneminder
    spec:
      nodeSelector:
        kubernetes.io/hostname: rem
      containers:
        - image: quantumobject/docker-zoneminder:latest
          imagePullPolicy: IfNotPresent
          command: [/bin/sh]
          args: [-c, "rm -rf /dev/shm/*; /sbin/my_init"]
          env:
            - name: ZM_DB_HOST
              value: 127.0.0.1
            - name: TZ
              value: America/New_York
            - name: SERVICE_PORTS
              value: "80"
          name: zoneminder
          resources: {}
          volumeMounts:
            - mountPath: /var/cache/zoneminder
              name: capture
            - mountPath: /dev/shm
              name: shm
        - image: mariadb:latest
          imagePullPolicy: IfNotPresent
          name: db
          env:
            # These values are literally hardcoded in quantumobject/zoneminder
            # (ugh), so no need to really keep them private
            - name: MYSQL_USER
              value: zmuser
            - name: MYSQL_PASSWORD
              value: zmpass
            - name: MYSQL_DATABASE
              value: zm
            - name: MYSQL_ROOT_PASSWORD
              value: mysqlpsswd
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zoneminder-data
        - name: capture
          hostPath:
            path: /mnt/storage/Kevin/Computing/Data/ZoneMinder
        - name: shm
          emptyDir:
            medium: Memory
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zoneminder
  name: zoneminder
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: zoneminder
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: zoneminder
spec:
  tls:
    - secretName: zoneminder-tls
      hosts:
        - zm.potatofrom.space
  rules:
  - host: zm.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: zoneminder
          servicePort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: zoneminder
  name: zoneminder-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
