apiVersion: v1
data:
  Corefile: |-
    .:10053 {
                errors
                health :10054
                kubernetes cluster.local in-addr.arpa ip6.arpa {
                  pods insecure
                  upstream
                  fallthrough in-addr.arpa ip6.arpa
                }
                prometheus :10055
                proxy . 1.1.1.1:53
                cache 30
                loop
                reload
                loadbalance
              }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:10053 {\n            errors\n            health :10054\n            kubernetes cluster.local in-addr.arpa ip6.arpa {\n              pods insecure\n              upstream\n              fallthrough in-addr.arpa ip6.arpa\n            }\n            prometheus :10055\n            proxy . /etc/resolv.conf\n            cache 30\n            loop\n            reload\n            loadbalance\n          }"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kube-dns","kubernetes.io/cluster-service":"true"},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2018-11-10T21:04:45Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: coredns
  namespace: kube-system
  resourceVersion: "35910881"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 4099fc5f-e52c-11e8-9c0a-4e165c3ccd4a
