apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    k8s-app: gitlab
  name: gitlab
spec:
  ports:
  - name: "22"
    port: 22
    targetPort: 22
  selector:
    k8s-app: gitlab
status:
  loadBalancer: {}
