apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack.yml
    kompose.version: 1.9.0 (HEAD)
  creationTimestamp: null
  labels:
    k8s-app: mail
  name: mail
spec:
  ports:
  - name: "25"
    port: 25
    targetPort: 25
  - name: "143"
    port: 143
    targetPort: 143
  - name: "587"
    port: 587
    targetPort: 587
  - name: "993"
    port: 993
    targetPort: 993
  selector:
    k8s-app: mail
status:
  loadBalancer: {}
