repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: coreos
    url: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    version: 1.7.0
    values:
      - ./values/nginx-ingress.yaml
  - name: nfs-client-provisioner
    namespace: kube-system
    chart: ./charts/nfs-client-provisioner
  - name: cert-manager
    namespace: kube-system
    chart: stable/cert-manager
    version: 0.5.0
    values:
      - ./values/cert-manager.yaml
  - name: gitlab
    namespace: default
    labels:
      has-migrations: "true"
    chart: gitlab/gitlab
    version: 1.9.1
    values:
      - ./values/gitlab.yaml
      - ./values/gitlab.secret.yaml
  - name: mastodon
    namespace: default
    labels:
      has-migrations: "true"
    chart: ./charts/mastodon
    values:
      - ./values/mastodon.yaml
      - ./values/mastodon.secret.yaml
  - name: mc-will-sf4
    namespace: default
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-will-sf4.yaml
  - name: factorio
    namespace: default
    chart: stable/factorio
    values:
      - ./values/factorio.yaml
  - name: nextcloud
    namespace: default
    chart: ./charts/nextcloud
    values:
      - ./values/nextcloud.yaml
      - ./values/nextcloud.secret.yaml
  - name: postgresql
    namespace: default
    chart: stable/postgresql
    version: 5.3.10
    values:
      - ./values/postgresql.yaml
      - ./values/postgresql.secret.yaml
  - name: mariadb
    namespace: default
    chart: stable/mariadb
    version: 6.5.9
    values:
      - ./values/mariadb.yaml
      - ./values/mariadb.secret.yaml
  - name: kubecfg
    namespace: default
    chart: ./charts/kubecfg
    values:
      - ./values/kubecfg.yaml
      - ./values/kubecfg.secret.yaml