repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: gitlab
    url: https://charts.gitlab.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    version: 1.39.1
    values:
      - ./values/nginx-ingress.yaml
  # - name: nfs-client-provisioner
  #   namespace: kube-system
  #   chart: ./charts/nfs-client-provisioner
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.15.1
    values:
      - ./values/cert-manager.yaml
  - name: mastodon
    namespace: default
    labels:
      mastodon: "true"
      has-migrations: "true"
    chart: ./charts/mastodon
    values:
      - ./values/mastodon.yaml
      - ./values/mastodon.secret.yaml
  - name: postgresql
    namespace: default
    chart: bitnami/postgresql
    version: 8.10.5
    values:
      - ./values/postgresql.yaml
      - ./values/postgresql.secret.yaml
  - name: mariadb
    namespace: default
    chart: bitnami/mariadb
    version: 7.5.1
    values:
      - ./values/mariadb.yaml
      - ./values/mariadb.secret.yaml
  - name: kliu-gitlab-runner
    namespace: default
    chart: gitlab/gitlab-runner
    version: 0.17.1
    values:
      - ./values/kliu-gitlab-runner.secret.yaml
  - name: scintillating-gitlab-runner
    namespace: default
    chart: gitlab/gitlab-runner
    version: 0.17.1
    values:
      - ./values/scintillating-gitlab-runner.secret.yaml
  - name: kubecfg
    namespace: default
    labels:
      kubecfg: "true"
    chart: ./charts/kubecfg
    values:
      - ./values/kubecfg.yaml
      - ./values/kubecfg.secret.yaml
