repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    version: 1.29.6
    values:
      - ./values/nginx-ingress.yaml
  - name: nfs-client-provisioner
    namespace: kube-system
    chart: ./charts/nfs-client-provisioner
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.10.1
    values:
      - ./values/cert-manager.yaml
  - name: gitlab
    namespace: default
    labels:
      has-migrations: "true"
      gitlab: "true"
    chart: gitlab/gitlab
    version: 2.6.7
    values:
      - ./values/gitlab.yaml
      - ./values/gitlab.secret.yaml
  - name: mastodon
    namespace: default
    labels:
      has-migrations: "true"
    chart: ./charts/mastodon
    values:
      - ./values/mastodon.yaml
      - ./values/mastodon.secret.yaml
  - name: mc-carta
    namespace: default
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-carta.yaml
  - name: mc-ralph
    namespace: default
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-ralph.yaml
  - name: mc-rlcraft
    namespace: default
    labels:
      x: "true"
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-rlcraft.yaml
    # Requested by Steven, Will 2019-12-23
  - name: mc-ftb-academy
    namespace: default
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-ftb-academy.yaml
  - name: mc-rohan
    namespace: default
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-rohan.yaml
  - name: mc-will-sf4
    namespace: default
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-will-sf4.yaml
    # Will MC.Eternal
  - name: mc-will-eternal
    namespace: default
    chart: ./charts/minecraft
    values:
      - ./values/mc.yaml
      - ./values/mc-will-eternal.yaml
  - name: factorio
    namespace: default
    chart: stable/factorio
    values:
      - ./values/factorio.yaml
  - name: nextcloud
    namespace: default
    chart: ./charts/nextcloud
    values:
      - ./values/nextcloud.yaml
      - ./values/nextcloud.secret.yaml
  - name: postgresql
    namespace: default
    chart: stable/postgresql
    version: 5.3.10
    values:
      - ./values/postgresql.yaml
      - ./values/postgresql.secret.yaml
  - name: mariadb
    namespace: default
    chart: stable/mariadb
    version: 6.5.9
    values:
      - ./values/mariadb.yaml
      - ./values/mariadb.secret.yaml
  - name: gitlab-runner
    namespace: default
    chart: gitlab/gitlab-runner
    version: 0.9.0
    values:
      - ./values/gitlab-runner.secret.yaml
  - name: kubecfg
    namespace: default
    chart: ./charts/kubecfg
    values:
      - ./values/kubecfg.yaml
      - ./values/kubecfg.secret.yaml
