{
  chunkserver = ''
    PERFORM_FSYNC = 0
    NICE_LEVEL = 5
    HDD_PUNCH_HOLES = 1
    ENABLE_LOAD_FACTOR = 1
    NR_OF_NETWORK_WORKERS = 10
    NR_OF_HDD_WORKERS_PER_NETWORK_WORKER = 4
    HDD_TEST_FREQ = 3600
  '';
}
