apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  serviceName: onlyoffice-documentserver
  selector:
    matchLabels:
      app: onlyoffice-documentserver
  template:
    metadata:
      labels:
        app: onlyoffice-documentserver
    spec:
      containers:
        - image: onlyoffice/documentserver
          name: onlyoffice-documentserver
          volumeMounts:
            - mountPath: /var/log/onlyoffice
              name: data
              subPath: logs
            - mountPath: /var/www/onlyoffice/Data
              name: data
              subPath: data
            - mountPath: /var/lib/onlyoffice
              name: data
              subPath: lib
            - mountPath: /var/lib/postgresql
              name: data
              subPath: postgresql
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: onlyoffice-documentserver-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: onlyoffice-documentserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: onlyoffice-documentserver
  name: onlyoffice-documentserver-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 4g
  name: onlyoffice-documentserver
spec:
  tls:
    - secretName: onlyoffice-documentserver-tls
      hosts:
        - ood.kliu.io
  rules:
    - host: ood.kliu.io
      http:
        paths:
          - path: /
            backend:
              serviceName: onlyoffice-documentserver
              servicePort: 80
