apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      nodeSelector:
        kubernetes.io/hostname: rem
      containers:
      - image: gitea/gitea:1.4.1
        name: gitea
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitea-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitea
  name: gitea-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: gitea
spec:
  tls:
    - secretName: gitea-tls
      hosts:
        - git.potatofrom.space
  rules:
  - host: git.potatofrom.space
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea
          servicePort: 3000