- name: Install latest mergerfs package
  apt:
    deb: https://github.com/trapexit/mergerfs/releases/download/2.32.1/mergerfs_2.32.1.debian-buster_amd64.deb
- name: Initialize mergerfs mount
  mount:
    src: /mnt/data*:/mnt/wdgreen1tb
    path: /mnt/storage
    fstype: fuse.mergerfs
    opts: use_ino,cache.files=partial,dropcacheonclose=true,allow_other,category.create=mfs,noforget
    state: present
- name: Install snapraid
  apt:
    deb: https://bintray.com/openmediavault-plugin-developers/usul/download_file?file_path=pool%2Fmain%2Fs%2Fsnapraid%2Fsnapraid_11.5-1_amd64.deb
- name: Install snapraid service
  copy:
    src: ../files/snapraid.service
    dest: /etc/systemd/system
    mode: 0644
    owner: root
    group: root
- name: Install snapraid timer
  copy:
    src: ../files/snapraid.timer
    dest: /etc/systemd/system
    mode: 0644
    owner: root
    group: root
- name: Install snapraid configuration
  copy:
    src: ../files/snapraid.conf
    dest: /etc/
    mode: 0644
    owner: root
    group: root
- name: Enable snapraid timer
  systemd:
    name: snapraid.timer
    state: started
    enabled: yes
