- name: Start Ethereum mining docker container
  docker_container:
    timeout: 600
    name: ethminer
    state: present
    image: cryptojunkies/claymore:eth-amd-latest
    command:
      [
        -epool,
        "eth-us-east1.nanopool.org:9999",
        -ewal,
        0xA0fd60A944c1f86D529EEbEf19b34ca61294Ffe5/rem,
        -epsw,
        x,
      ]
    restart_policy: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
    security_opts: [seccomp:unconfined]
    groups: [video]