- hosts: all
  become: yes
  roles:
    - system
    - monit
    - mosh
- hosts: homelab-cluster.i.kliu.io
  become: yes
  roles: [ddns]
- hosts: karmaxer.i.kliu.io
  become: yes
  vars_files:
  - vars/main.secret.yml
  roles:
    - duplicacy
    - snapraid
    - nfs-server
    - borg-server
- hosts: homelab-cluster.i.kliu.io,transmission.i.kliu.io
  become: yes
  roles: [storage-mount]
- hosts: storj_nodes
  become: yes
  roles:
    - role: storj-rclone
      tags: storj
