- hosts: all
  become: yes
  roles:
  - mosh
- hosts: rem.i.kliu.io
  become: yes
  roles:
  - duplicacy
  - snapraid
  - nfs-server
  - borg-server
- hosts: nfs_clients
  become: yes
  roles:
  - nfs-client