- hosts: all
  become: yes
  roles:
    - mosh
    - system
- hosts: homelab-cluster.i.kliu.io
  become: yes
  roles: [ddns]
- hosts: rem.i.kliu.io
  become: yes
  roles:
    - ethminer
    - duplicacy
    - snapraid
    - nfs-server
    - borg-server
- hosts: storj_nodes
  become: yes
  roles:
    - role: storj-rclone
      tags: storj
