- hosts: all
  become: yes
  tags: [start]
  roles:
    - system
    - mosh
- hosts: homelab-cluster
  become: yes
  roles: [ddns, monit]
- hosts: karmaxer
  become: yes
  vars_files:
    - vars/main.secret.yml
  roles:
    - duplicacy
    - snapraid
    - nfs-server
    - borg-server
    - monit
- hosts: homelab-cluster,transmission
  become: yes
  roles: [storage-mount]
- hosts: storj_nodes
  become: yes
  roles:
    - role: storj-rclone
      tags: storj
