# - hosts: all
#   become: yes
#   roles:
#   - mosh
# - hosts: rem.i.kliu.io
#   become: yes
#   roles:
#   - duplicacy
#   - snapraid
#   - nfs-server
#   - borg-server
- hosts: storj_nodes
  become: yes
  roles:
  - storj-rclone