- hosts: rem.i.kliu.io
  become: yes
  tasks:
  - name: Start ethereum miner docker container
    docker_container:
      name: claymore
      image: cryptojunkies/claymore:eth-amd-latest
      devices: [/dev/dri, /dev/kfd]
      privileged: yes
      command: [-epool, stratum+tcp://eth-us-east1.nanopool.org:9999, -ewal 0xA0fd60A944c1f86D529EEbEf19b34ca61294Ffe5.rem, -epsw x]
      restart: yes
      restart_policy: unless-stopped
  - name: Ensure NFS utilities are installed
    apt:
      name: nfs-kernel-server
      state: present
  - name: add NFS bind mount
    mount:
      src: /mnt/storage
      path: /srv/nfs4/storage
      fstype: none
      opts: bind
      state: mounted
  - name: copy /etc/exports
    template: src=files/exports.j2 dest=/etc/exports owner=root group=root
    notify: [re-export NFS filesystems]
  handlers:
  - name: re-export NFS filesystems
    command: exportfs -ra
- hosts: 'homelab-cluster.i.kliu.io,root@transmission.i.kliu.io'
  become: yes
  tasks:
  - name: install NFS mount utils
    apt:
      name: nfs-common
      state: present
  - name: add NFS mount to fstab
    mount:
      src: 192.168.1.5:/storage
      path: /mnt/storage
      fstype: nfs
      opts: retry=10000
      state: mounted