- hosts: all
  become: yes
  roles:
    - system
    - monit
    - mosh
- hosts: homelab-cluster.i.kliu.io,transmission.i.kliu.io
  become: yes
  roles: [storage-mount]
- hosts: homelab-cluster.i.kliu.io
  become: yes
  roles: [ddns]
- hosts: rem.i.kliu.io
  become: yes
  roles:
    - ethminer
    - duplicacy
    - snapraid
    - nfs-server
    - borg-server
- hosts: storj_nodes
  become: yes
  roles:
    - role: storj-rclone
      tags: storj
