apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        postgresql-client: "true"
        app: {{ template "fullname" . }}-web
    spec:
      containers:
      - name: {{ template "fullname" . }}-web
        image: {{ .Values.image | quote }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        args: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
        envFrom:
          - secretRef:
              name: {{ template "fullname" . }}-secrets
          - configMapRef:
              name: {{ template "fullname" . }}-config
        ports:
        - name: web
          containerPort: 3000
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: web-system
          mountPath: /mastodon/public/system
      volumes:
      - name: web-system
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingSystemClaim | default (include "fullname" .) }}-web-system

