apiVersion: batch/v1beta1
kind: CronJob
metadata:
  # Unique key of the Job instance
  name: {{ template "fullname" . }}-daily
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    metadata:
      name: {{ template "fullname" . }}-daily
    spec:
      template:
        metadata:
          labels:
            postgresql-client: "true"
        spec:
          restartPolicy: Never
          containers:
          - name: {{ template "fullname" . }}-daily
            image: {{ .Values.image | quote }}
            imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
            args: [sh, -c, "tootctl media remove && tootctl preview_cards remove --days 30"]
            envFrom:
              - secretRef:
                  name: {{ template "fullname" . }}-secrets
              - configMapRef:
                  name: {{ template "fullname" . }}-config
            resources:
{{ toYaml .Values.resources | indent 14 }}
            volumeMounts:
            - name: web-system
              mountPath: /mastodon/public/system
          volumes:
          - name: web-system
            persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingSystemClaim | default (include "fullname" .) }}-web-system
