- name: Copy SMB credentials
  copy:
    src: smbcredentials.secret.txt
    dest: /.smbcredentials
    owner: root
    group: root
    mode: 0400
- name: Install NFS mounting programs
  apt:
    name: nfs-common
    state: present
- name: add storage NFS mount
  mount:
    src: karmaxer.fios-router.home:/storage
    fstype: nfs
    path: /mnt/storage
    opts: defaults,nofail
    state: mounted
